import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Poppins } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

const jakarta_sans = Plus_Jakarta_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${jakarta_sans.className} antialiased`}
        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  );
}
